### ISSUE TITLE
Docs Missing

### ISSUE THREAD

**Issue by joshblum** [chrissimpkins/naked#15]
Is this project still active? The docs link to a 404 :/ 
![screen shot 2016-10-27 at 10 21 26](https://cloud.githubusercontent.com/assets/1144020/19770940/274a0ca6-9c2f-11e6-8d10-c654e32023e5.png)

**Comment by maxicecilia** [comment]
Found them here: http://naked.readthedocs.io/

**Comment by joshblum** [comment]
Closed by #16

**Comment by pparidans** [comment]
Hi,
The website still points to a 404 (using http://docs.naked-py.com/).

**Comment by ChildishGiant** [comment]
https://pypi.org/project/Naked/ PyPI still has 4 links to the dead site
