### ISSUE TITLE
homepage docs link is broken

### ISSUE THREAD

**Issue by alexjurkiewicz** [chrissimpkins/naked#18]
http://naked-py.com/ docs link should point to http://naked.readthedocs.io/

**Comment by chrissimpkins** [comment]
thank you!  I fixed all of the links.  I don't have the original domain name any longer and it seems it is pointing elsewhere :)

**Comment by Sibgatulin** [comment]
I am afraid [the page on pypi](https://pypi.org/project/Naked/) still links to the old domain, maybe worth updating too.
