### ISSUE TITLE
Why can't naked see node.js?

### ISSUE THREAD

**Issue by DgDays** [chrissimpkins/naked#22]
There is such a problem: installed node.js and naked library, but naked does not want to work with node.js (((Here is the error: "
Exit Status 1: b '"node" is not an internal or external \ r \ n command, an executable program or a batch file. \ R \ n' "Please help me solve this problem. Node.js has already been installed on the disk itself (neither in some of the folders, but directly to the C:\ drive)

![image](https://user-images.githubusercontent.com/55804305/99539203-bfeecf00-29cf-11eb-9ef4-a59bc9fbdc6a.png)
![image](https://user-images.githubusercontent.com/55804305/99539226-c9783700-29cf-11eb-83b8-ba2581c42a92.png)

**Comment by DgDays** [comment]
Forgive me if I translated it into English. I myself speak Russian and it’s a bit difficult for me ...

**Comment by chrissimpkins** [comment]
It's been some time since I worked on this package.  It may be that is not properly designed to call node on Win.  Do you need to use `node.exe` instead of `node` when you execute node on your command line?

**Comment by DgDays** [comment]
node also works on win, but for some reason I do not understand it writes that it allegedly does not exist (although everything is ok in cmd)

**Comment by chrissimpkins** [comment]
Mind checking what output you get from the following Python script in your Win environment?

#### nodecheck.py

```python
import os
import subprocess

os.system("node --version")
subprocess.check_output(["node", "--version"])
```

**Comment by DgDays** [comment]
in the output I get the node version

**Comment by chrissimpkins** [comment]
It is listed twice?  Once from each of those statements?

**Comment by DgDays** [comment]
no, only this one gives the version

`os.system("node --version")`

**Comment by DgDays** [comment]
Good afternoon! Solved the problem by replacing `subprocess.check_output` with `subprocess.run`. Now everything is work) Perhaps the solution is clumsy, but working
